<?php

// +----------------------------------------------------------------------
// | ThinkAdmin
// +----------------------------------------------------------------------
// | 版权所有 2014~2017 广州楚才信息科技有限公司 [ http://www.cuci.cc ]
// +----------------------------------------------------------------------
// | 官方网站: http://think.ctolog.com
// +----------------------------------------------------------------------
// | 开源协议 ( https://mit-license.org )
// +----------------------------------------------------------------------
// | github开源项目：https://github.com/zoujingli/ThinkAdmin
// +----------------------------------------------------------------------
namespace app\index\controller;
use JiaweiXS\WeApp\WeApp;
use think\Controller;
use think\Db;
/**
 * 应用入口控制器
 * @author Anyon <zoujingli@qq.com>
 */
class Adv extends Controller
{
    public $domain;
    public function  initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->domain =  input('server.SERVER_NAME');
    }

  //更多好玩设置
    public function update(){
        cache($this->domain.'morefun',[]);
    }
    //更多好玩展示
    public function show(){
        $cachename =$this->domain.'morefun';
        $adv = input('adv',0);
        $appid = input('appid');
        $data = cache($cachename);
        $result = @$data[$appid][$adv];
        if(!empty($result)){
            return json_encode($result);
        }
        $param['adv'] =$adv;
        $param['appid'] =$appid;
        $res = makeRequest('http://account.v1kj.cn/api/index/getadv',$param);
        $result = @json_decode($res['result'],true);
        if(empty($result)){
            return json_encode(['code'=>400]);
        }
        $data[$appid][$adv] = $result;
        cache($cachename,$data,86400*7);
        return json_encode($result);
    }
}


